services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 3071:5432
    environment:
      POSTGRES_USER: demo-user
      POSTGRES_PASSWORD: demo-password

  server:
    build: ./server
    container_name: server
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://127.0.0.1:3071/
      DB_LOGIN: demo-user
      DB_PASSWORD: demo-password
    depends_on:
      - db